function makePoem() {
      	numLines = Math.floor((Math.random()*30)+5);
      	line = getLine();
      	repeatedLine = getLine();
      	repeatingLines = Math.floor((Math.random()*10)+1);
      	
      	document.write ("<h2>" + repeatedLine + "</h2>");
      	if(repeatingLines < 4) { line = repeatedLine + "<br />" + line; }
      	for(var i=0; i<numLines; i++)
      	{
      		if(numLines > 15)
      		{
      			paragraph = Math.floor((Math.random()*10)+1);
      			if(paragraph > 7)
      			{
      				if(paragraph > 9)
      				{
      					line += "<br />" + repeatedLine;
      				}
      				line += "<br />";
      			}
      		}
      		if(repeatingLines > 5 && numLines < 10)
      		{
      			line += "<br />" + repeatedLine;
      		}
      		line += "<br />" + getLine();
     		punctuation = Math.floor((Math.random()*20)+1);
      		if(punctuation == 1) { line += "!"; }
      		if(punctuation == 2) { line += "?"; }
      		if(punctuation == 3) { line += ":"; }
		}
		if(repeatingLines > 7) { line += "<br />" + repeatedLine; }
		document.write(line);
}

function getLine() {
var strings = [
'Poised for the flight to peace on joyous wings',
'We settle in silence \'mid the morning\'s roar',
'An iPod buzzes, a bicycle rings',
'Quakers, meeting',
'The Silence warms me',
'To recharge my batteries',
'Meeting for Worship',
'Tick, tock, tick, tock, tick, tock',
'Together, in Community',
'Silence',
'Cathedral bells solemnly chime the hour',
'Footsteps, a car drives by, dogs bark',
'And footballers cheer in the nearby park',
'There, the sough of the wind in the sky-tall trees',
'Here, a covered cough, a smothered sneeze',
'The clock softly ticks',
'A heater clicks',
'Door squeaks',
'Chair creeks',
'Stillness',
'The quiet door opens to a hollowed calm',
'While a small bird sings',
'Like a demolition site',
'My world',
'Stands in ruins',
'Neglect and damage leaves',
'The carefully constructed buildings',
'Of my life',
'In rubble at my feet',
'Pain, destruction, confusion',
'The ugly part of reconstruction',
'To be lived through',
'Holding, however feebly, to the vision',
'Of new buildings',
'New life',
'Quakers, chatting',
'Busy, busy, busy',
'The silent Meeting',
'New creation',
'If, in the silence of meeting, we encounter the Still Small Voice, we become mystics',
'If we acknowledge the self within us to be the same essence as the self in each other',
'We are approaching knowledge that we belong to the Great Self',
'If we can say that self-knowledge is the Way the Truth and the Life',
'And become aware that \'no man cometh to the Father but through this realisation\', we begin to understand Jesu\'s way',
'If we have at any time in our lives experienced something Numinous',
'Something at present scientifically unsolved, something we feel belongs to the spiritual',
'Then we have felt the calling to be a searcher, to seek that Dimension',
'If we have heard or seen within our souls, a glimpse through Time\'s shadow-screen',
'At that moment we were mediums for prophesy, and glimpsed eternity',
'These things are there for us. All is there for everyone',
'These things are fundamentals, the source of all religions',
'This is my fundamentalism',
'But \'isms\' and \'ists\' stereotype. They are dangerous',
'The danger is in ourselves &mdash; pigeon-holing',
'Deep down, my soul is one with Quakerism',
'It is also one with Islam through the Sufi mystics',
'Neither can I argue with the Sikh, the Hindu, the Muslim, or the Buddhist',
'And Jesus is my life-long guide',
'Does this make me a \'pluralist\'',
'I think most emphatically not',
'Just a fundamentalist',
'My God, my God',
'Wherein gentle admonition',
'Wherein word of \'that\'s so good\'',
'Wherein light on precious text',
'Wherein guide in dark confusion','In thee',
'Wherein reins that hold back ego',
'Wherein reasoned argument',
'Wherein wealth of understanding',
'Wherein no thought of self but others',
'Wherein passion for the quiet voice',
'Wherein leads the trembling heart',
'Wherein courage to face the assembled',
'Wherein the timid thought let loose',
'Wherein the heart that swallows pride',
'Wherein the heart that takes no bow',
'Wherein the heart that e\'er be with us',
'Wherein the heart that leaves us now',
'In thee',
'You think you are alone',
'Did you not know',
'That somewhere, perhaps far distant',
'But close in the world of spirit',
'Into the stillness a voice has spoken your name',
'Into the darkness a thought has travelled',
'In the cold of winter love has lit a flame',
'That burns unfailing',
'The thought, the word, the flame',
'Live on',
'There to take and to hold',
'Awaiting only',
'Recognition and acceptance',
'Journeying, struggling, searching',
'Heavy clouds',
'Confusion in the darkness',
'Seeking answers in the light',
'Finding the way, following the path',
'Meeting Friends',
'Travelling together in the darkness',
'Praying for healing in the light',
'Worship group exploring, centring',
'Lighting candles',
'Meditating in the darkness',
'Listening to music in the light',
'Traditions, faiths, cultures',
'Celebrating community',
'Universal Spirit flowing over the darkness',
'Building bridges in the light',
'Relaxing, learning, experimenting',
'Quaker croquet',
'Hand bells ringing from the darkness',
'Creating harmony in the light',
'Making boxes in the stillness',
'Arts and craft',
'Symbolic collage depicting darkness',
'Turning radiant in the light',
'New songs, old songs, spiritually moving',
'Quaker song book',
'Music notes spring from the darkness',
'Finding voices in the light',
'Truth, beauty in the landscape',
'Wading birds',
'Silent watching in the darkness',
'Experiencing the power of light',
'Answering pain with courage',
'Salvaging the sacred',
'Helping others shine through their darkness',
'Receiving new light',
'Beautiful pictures, move, inspire',
'Works of art',
'Stations of the Cross in the darkness',
'Reflecting in the light',
'Holding hands in circles',
'Hugs of comfort',
'Personal shadows in the darkness',
'Dancing in the light',
'Threatening wind, rain and thunder',
'Deep ministry',
'Reach for a star in the darkness',
'New moon shedding light',
'100 children playing, singing',
'Silently enter',
'Bubbles blown float through the darkness',
'Rainbows of light',
'Gossamer cobweb coloured ribbons',
'Written words',
'Peace, trust, love rise above the darkness',
'Hanging in the light',
'Himalayan proverb of the journey',
'Walking, seeking',
'Hear the Spirit call in the darkness',
'Time to return in the light',
'Journey began in chaos, confusion',
'Burdened, ladened',
'Overcoming the tunnel of darkness',
'A spark of healing light',
'Down here in the dust',
'Under the choir stalls',
'It\'s very quiet',
'And the flagstones are cold',
'But the tiny carving',
'On the upturned bottom',
'Of this seat',
'Is smooth and warm',
'They\'re playing tug-of-war',
'With a stick from the river',
'Dragon grinning',
'Paws braced to pull',
'I can almost hear him growl',
'Worship, worship',
'But St Michael\'s not afraid',
'Of those twin rows of teeth',
'Or of being splattered with mud',
'Dragon\'s coat is leather',
'They\'ll get home safely',
'With four such capacious wings',
'These flowers so tenderly displayed',
'Soft pastel shades blending',
'Reflected in the Meeting house table',
'And these golden blossoms',
'Their bright faces gleaming',
'From a card, sent with loving messages',
'From Israel',
'And the lilies of the field near Bethlehem',
'Are still arrayed in glory',
'And nurtured',
'By God\'s hand',
'May he grant that all our flowers',
'Be watered',
'By the gentle benediction of rain',
'And not by children\'s tears',
'We grieve',
'We grieve for the victims of war',
'We grieve for preparing for more',
'We grieve for confusion of mind',
'We grieve for the cruel and unkind',
'We grieve for the children of these',
'We grieve for those on their knees',
'For the waste of resources of Earth',
'And those who are waiting for birth',
'We\'re committed to the finding of Peace',
'We\'re committed to people\'s release',
'From mis-information and lies',
'And the innocent child who just dies',
'We\'re committed to the sowing of love',
'Combining all things from above',
'Humanity surely must find',
'Some feelings beyond those of mind',
'Can it be true that',
'We are made of star dust',
'And living on a world',
'Whirling round the sun',
'How is that we',
'Have come to be',
'On this planet Earth',
'Seeing proof of divinity',
'Are we part of',
'The Eternal Mind',
'Eternally re-creating',
'Creation\'s paradigm',
'Milton said that we arrive',
'Trailing clouds of glory',
'Could they be reflected',
'In imagination\'s memory',
'Evolving with sensitivity',
'Through darkness to light',
'We may find in ourselves',
'Inspiration for creativity',
'A strange peace',
'This dead silence',
'Of the heart monitor',
'Which beats no more',
'Still the mother wails',
'In a refugee camp',
'And angry young men shoot',
'The prophet calls',
'\'They say peace\', \'peace\'',
'But there is no peace for our people',
'A strange freedom indeed',
'In this empty quarter',
'Who are you to judge me for what I eat',
'I\'m thankful',
'The Meeting room table',
'Quaker Faith and Practice',
'Advices and Queries',
'Silent worship',
'Centring, silently',
'In the Moonlight',
'Together, in the Circle',
'The Elders watch, the Overseers look, the Clerk nods',
'We are at peace',
'Be still',
'The still, small voice',
'To know God',
'Silence, loving',
'Silence, healing',
'Who are you to judge me for where I live',
'Who are you to judge me for my job',
'Who are you to judge me for where I go at night',
'Who are you to judge me for how I live my life',
'I\'m thankful I can live at all',
'Divine Spirit &mdash; indwelling all creation',
'From everlasting to everlasting',
'Awakening to this sacred presence within',
'It makes me aware of the responsibility',
'This universal gift entails upon me',
'To collaborate, serving the true',
'The good, the beautiful',
'Helping to provide the right conditions',
'For the sharing of what unifies',
'With awe and wonder I realise',
'Our total interdependence',
'Stop a while',
'Breathe',
'Touch heaven, not hell',
'Move again now',
'At a different pace',
'Into his hands he took some bread',
'Two fish and lo! Five thousand fed',
'\'Learning to share\', at last began',
'Behold the \'teaching\' Jesus man',
'His words worked in one like a yeast',
'The simple meal became a feast',
'From jugs of water, fine wine ran',
'See now the, \'changing-all-things\' man',
'He loved the poor and cured the lame',
'And rescued women on the game',
'Mosaic vengeance he did ban',
'This \'peaceful-revolution\' man',
'He rode a mule &mdash; a city stirred',
'And rushed to meet him with that word &mdash; \'Hosanna\' &mdash; loud the voices sang',
'Praise for the \'Allelujah\' man',
'Must debts be paid &mdash; the price is high',
'A cross is forged &mdash; a man must die',
'What part is this of what strange plan',
'Alas, the \'crucifixion\' man',
'Hands now washed',
'I stand holding them out',
'Beneath the air-puffing dryer',
'Watching the beads of water',
'Evaporate',
'I wonder at the change',
'Glinting droplets gone now &mdash; to what? to where',
'School-girl science offers water cycles',
'But I seek a soulful answer',
'To the matter of transformation',
'Silence forms and grows',
'All breathe, sigh; some cough, two speak',
'Hands clasp. God was here',
'Silent circle sits',
'Musing mundane, peace and war',
'Meaning. Friends sharing',
'Down through the sombre marches of these spaces',
'Between stone walls and barren places',
'Skies where the driven clouds flock',
'And the wind blusters in our faces',
'Roads that rise up like circling birds',
'Where the traveller settles on a hill\'s shoulder',
'My eye travels to the long horizons',
'I cannot find the easy words',
'Out of the silence like a light from a cloud',
'Comes a message of truth from God\'s love around',
'The gathered Meeting quickens to hear',
'The word of God from his presence near',
'Just as the wind through the door ajar',
'Conveys the scents of the world afar',
'Glimmers of God are sensed within',
'Enlightening and holding all again',
'We approach thee, dear God, in hopefulness',
'Trusting to grow in your blessed largess',
'May you continue to pour from your infinite height',
'Your life into ours, as we grow in your light',
'Tonight I was two souls',
'First by force and then by choice',
'This man makes his will, truth',
'And then I hear another voice',
'This voice gives a piteous cry',
'And from my pain I turn my eye',
'Lady, now you need not weep',
'Your beauty is for joy and song',
'The flower so long in darkness kept',
'Shall soon rejoice to see the Sun',
'That man, his will, his truth, will go',
'I am myself. Myself I\'ll know',
'Tonight I was two souls',
'Through blessing I became myself',
'The fear that makes me man grows less',
'The woman smiles, and moves to health',
'The man\'s protection rots her soul',
'When she can shed him, she\'ll be whole',
'Today I was two souls',
'A woman, sensual, sovereign',
'A man, whose fight for false ideals',
'Now falls away, an end to pain',
'He leaves behind the master\'s role',
'She welcomes him, and I am whole',
'Bring nothing but yourself',
'Your heart an open desert',
'Wide without boundaries',
'Small as an ancient monk\'s cell',
'Let the silence surround you',
'Enfold you in love',
'The stillness more active',
'Than the ways of the world',
'If nothing is said',
'Pay attention to its wisdom',
'If words are spoken',
'Listen to the heart of them',
'In yourself',
'Possess nothing',
'Receive all',
'The Lord is my shepherd',
'Why should I not want when so many have so little',
'I like the green pastures and still waters',
'He restores my soul',
'I like that as well',
'Should I not be led to good works for the sake of the Lord and others',
'The Valley of the Shadow of Death is a part of life &mdash; should I crave for protection from it',
'Your rod and staff comfort me',
'I like that',
'The table you prepare for me &mdash; should I not share it with my enemies',
'So that both our cups shall run over',
'Then we would all have a taste of your goodness and mercy',
'And all dwell together in your house here on earth',
'I am part of Thee',
'Thou art part of me',
'My time is imprinted',
'In your eternity',
'It is the tensions operating',
'Between the opposites',
'That make for life and strife',
'Awareness grows, as we make choices',
'Affecting the overall flow',
'As through this life we go',
'How to reconcile the opposites',
'Stand apart and rest awhile',
'Listen to the still, small voice',
'Reminding us: \'who is ruling you?\'',
'The imminent meets the transcendent',
'In a flash of recognition',
'How to \'walk cheerfully through this world!\'',
'It\'s not enough',
'To stay open and',
'Vulnerable',
'When the pain comes',
'As it will',
'To us or other people',
'We have to turn and face it',
'Full on',
'Let it wash over us',
'In a flood of Light',
'Trusting in the Rock',
'On which we stand',
'If Life becomes continuum of change',
'Then Death will be our ever-changing Life',
'Thus every death will have enormous range',
'Of possible effects where rumour\'s rife',
'The Truth of every rumour is in doubt',
'Uncertain knowledge, therefore, we must own',
'If Life\'s the state we\'re in, the Death will out',
'But which side of the Circle have we grown',
'Planted in the space within the womb',
'We might be from the Spirit in the air',
'Is our Essence on the Earth or in the tomb',
'Are Life and Death of One or form a pair',
'Enigmas of this kind become the crux',
'As to whether just one candle makes a lux',
'My God is not a he or a she',
'With a face and a crown',
'My God is everywhere:in you and me',
'My God is a bird on the wing',
'The wild white waves of the sea',
'The first pink blossom in spring',
'My God is the joy and laughter, pain and sorrow',
'And the birth of new life',
'With the hopes of tomorrow',
'My heaven is here and now to behold',
'As the bay reflects the sunset',
'And turns the mud to gold',
'Like a demolition site',
'My world',
'Stands in ruins',
'Neglect and damage leaves',
'The carefully constructed buildings',
'Of my life',
'In rubble at my feet',
'Pain, destruction, confusion',
'The ugly part of reconstruction',
'To be lived through',
'Holding, however feebly, to the vision',
'Of new buildings',
'New life',
'New creation',
'Silent worship among others about people, problems and prayers',
'Ordinary people, old and young rich and poor but open to inspiration to',
'Calls of conscience, making for caring citizens',
'Including the inspiration to work for international peace',
'Environmental care for the sake of the future',
'Trusting friends and neighbours in such a way that',
'Yobs so-called become young men',
'Onlookers on human life seeking to be',
'Force for good',
'Faced with the',
'Responsibility to bring all talents to good use',
'Inner, sometimes flickering light to guide us',
'Equally for all, for the young, the wayward, and the elderly to bring',
'New gospels for non-Friends as well as Friends, indeed for all',
'Desiring to drink the drops of wisdom',
'Society now needs more than in any previous century',
'A white horse I first thought I saw',
'But the spray of the wave turned into a claw',
'A dragon appeared next: as high as can be',
'And in an instant, it turned into a tree',
'The sea, in her anger, seemed to rise',
'Above all else, then I saw',
'Christ',
'He, majestically, floated on a crest of a wave',
'And I realised that all else had become but a grave',
'This must, I thought, be the End',
'And He has come to wash my sins away',
'Deep inside me, I knew all was as it should be',
'And at long last, I would be set free',
'No need for time now, for after all',
'He is the King of Kings',
'And all good tidings is what He brings',
'What fear should I have',
'When in Him there is only Love',
'The Lamb, the Son of God, who came from above',
'No, no fear at all',
'Him I believe in and in Him',
'I shall live in a light that is no longer dim',
'Praise Him, love Him, I am one of His fold',
'This, as a child, was what I was told',
'And now, as a grown-up, I should not be bold',
'All weekend I have listened to the sea',
'Have risen with the sea',
'Have slept with the sea',
'Have walked along the changing shoreline',
'The sun has risen, has set',
'The earth has changed its colours',
'The sky its colours, the voice its colours',
'The earth has groaned under the weight of the sea',
'I do not speak the language of the sea',
'Mine is an earth language, stuttering',
'A language which with its nets',
'Trawls the sky and stars and brings in the wind',
'On the sand now lie broken clauses',
'Verbs collect in pools',
'Nouns lie scattered',
'Earth and water sparkle with exclamation marks',
'Each is gestation and bringing forth',
'To let each impression and each germ of a feeling',
'Come to completion wholly in itself, in the dark',
'In the inexpressible, the unconscious',
'Beyond the reach of ones own intelligence',
'And await with deep humility and patience',
'The birth-hour of a new clarity',
'That alone is living the artists\' life',
'Being an artist means not reckoning and counting',
'But ripening like the tree which does not force its sap',
'And stands confident in the storms of spring',
'Without the fear that after them may come no summer',
'It does come. But it comes only to the patient',
'Who are there as though eternity lay before them',
'So unconcernedly still and wide',
'Quakers sitting',
'Quietly knitting',
'The weft of the eternal',
'With the warp of the world',
'The result',
'A patchwork quilt',
'To warm themselves',
'Or serve to comfort others',
'We watch, we listen',
'We get informed about happenings',
'In this, our divided world',
'Every news item has become \'a story\'',
'The greater the distress',
'At the sight of our divided world',
'The more our longing increases',
'To search what unifies, integrates',
'How to reach through the distress',
'How to heal the hurt',
'How to feel at one',
'With the alien, the unfamiliar, distant',
'The sun is always there',
'Woven if we can\'t see it',
'Love is ever present',
'Woven if we cannot feel it',
'Get in touch with your indwelling spirit',
'Find the One &mdash; in the Many',
'We came',
'We the women',
'We talked long',
'We walked well',
'We sang our song',
'In the firelight',
'Waiting for the moonrise',
'We spoke our joy',
'We wept our sorrow',
'We felt our power',
'We the women',
'We gather again',
'By the fireside',
'Our songs rose',
'Like leaping sparks',
'By the fireside',
'We felt the Spirit rise',
'The spirit of our youth',
'The spirit wise and old',
'Sisters the Spirit gathers us',
'Sisters we must rise',
'Our task is not yet done',
'Sisters love and sorrow',
'Sisters love and knowledge',
'Sisters love and wisdom',
'Will guide us in our power',
'Sisters come and gather',
'We change the world together',
'I rejoiced when they said to me',
'Let us go up to the House of Friends',
'At last my feet are standing in the Entrance',
'I am in the courtyard of the House',
'Friends House, built for all Friends',
'Where all the tribes can Meet',
'There all Friends meet for Business',
'To discern the Lord\'s Work',
'And as a sign to all that pass',
'To give thanks to the Lord',
'For there are set the tables of the Clerks',
'And there are the Books of Record',
'For there are sat the Women and Men for the Work of the Lord',
'And all are met to give Thanks',
'And sacrifice for the Work',
'For love of my Brothers and Sisters',
'I say \'Peace upon this House\'',
'I rejoiced when they said to Me',
'\'Let us go up to Jerusalem\'',
'Peace',
'What\'s peace? Now first of all it\'s really',
'Not a simple issue of no-war',
'It\'s no-injustice, no-intolerance, no-hatred',
'It\'s thinking good, not bad of everyone',
'It recognises one humanity',
'In which all lives are precious',
'And worthy to be loved and given help',
'Towards fulfilment',
'Peace is an inner state',
'Reflected outwardly in actions',
'In loving care for anyone in need',
'Its qualities are wisdom',
'And compassion',
'Our work for peace is work for harmony among all beings',
];

var randomIndex = Math.floor(Math.random() * strings.length);

var randomString = strings[randomIndex];

return randomString;
}

function getName() {
var firstNames = [
'Anna',
'Jonathan',
'Alan',
'Pauline',
'Lani',
'Sue',
'Judy',
'Simon',
'Craig',
'Oliver',
'Barney',
'Mary',
'Richard',
'Pat',
'Marge',
'Janet',
'Joe',
'Ken',
'Harvey',
'Paul',
'Lauren',
'Claire',
'Kay',
'Bob',
'Roger',
'Charles',
'Edward',
'George',
'Audrey',
'Diana',
'Iain',
'Sinead',
'Marlene',
'Rod',
'Pauline',
'Tim',
'Elaine',
'Miranda',
'Judith',
'Fiona',
'Kathleen',
'Pippa',
'Jane',
'Carolyn',
'Jeremy',
'Lee',
'Eleanor',
'Jamie',
'Ruth',
'Amy',
'Ruaridgh',
'Wendy',
'Jeff',
'Laurie',
'Siobhan',
'Daphne',
'Roberta',
'Gerald',
'Joanna',
'Gregory',
'Amelia',
'Malcolm',
'Fiona',
'Michael',
'Maggie',
'Clifford',
'Keith',
'Barbara',
'Shelagh',
'Melvyn',
'Nick',
'Lisa',
'Rebecca',
]

var secondNames = [
'Gray',
'Smith',
'Taylor',
'Jones',
'Bradford',
'Johnson',
'Green',
'Endersby',
'Hawthorne',
'Williams',
'Grant',
'McCrimmon',
'Pond',
'Wagner',
'Carolan',
'Ford',
]

randomIndex = Math.floor(Math.random() * firstNames.length);
byline = "<p><em>" + firstNames[randomIndex];
randomIndex = Math.floor(Math.random() * secondNames.length);
byline += " " + secondNames[randomIndex] + "</em></p>";

return byline;
}
